version: '3.5'

services:
  postgres:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
      - ./seed_db:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5007:5007"
    env_file:
    - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
    - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  pdf-service:
    build:
      context: ./go-service
    container_name: pdf-service
    ports:
      - "8081:8081"
    env_file:
    - ./go-service/.env
    depends_on:
      - backend
    
volumes:
  data:
